-- Globaler Übungskatalog (deutsche Namen, englische Aliase für die Suche). user_id = null.
insert into public.exercises (name, aliases)
select v.name, v.aliases
from (values
  ('Kniebeuge', array['Back Squat', 'Langhantel-Kniebeuge']::text[]),
  ('Frontkniebeuge', array['Front Squat']::text[]),
  ('Kniebeuge mit Pause', array['Pause Squat']::text[]),
  ('Goblet Squat', array[]::text[]),
  ('Bulgarian Split Squat', array['Bulgarische Kniebeuge']::text[]),
  ('Ausfallschritte', array['Lunges']::text[]),
  ('Ausfallschritte gehend', array['Walking Lunges']::text[]),
  ('Beinpresse', array['Leg Press']::text[]),
  ('Hackenschmidt-Kniebeuge', array['Hack Squat']::text[]),
  ('Beinstrecker', array['Leg Extension']::text[]),
  ('Beinbeuger liegend', array['Leg Curl', 'Lying Leg Curl']::text[]),
  ('Beinbeuger sitzend', array['Seated Leg Curl']::text[]),
  ('Kreuzheben', array['Deadlift', 'Conventional Deadlift']::text[]),
  ('Rumänisches Kreuzheben', array['RDL', 'Romanian Deadlift']::text[]),
  ('Sumo-Kreuzheben', array['Sumo Deadlift']::text[]),
  ('Straight-Leg-Kreuzheben', array['Stiff-Leg Deadlift']::text[]),
  ('Hip Thrust', array['Hüftstoßen']::text[]),
  ('Glute Bridge', array['Beckenheben']::text[]),
  ('Good Morning', array[]::text[]),
  ('Hyperextensions', array['Rückenstrecker']::text[]),
  ('Wadenheben stehend', array['Standing Calf Raise']::text[]),
  ('Wadenheben sitzend', array['Seated Calf Raise']::text[]),
  ('Abduktoren-Maschine', array['Hip Abduction']::text[]),
  ('Adduktoren-Maschine', array['Hip Adduction']::text[]),
  ('Kabel-Kickback', array['Cable Kickback', 'Glute Kickback']::text[]),
  ('Bankdrücken', array['Bench Press', 'Flachbankdrücken']::text[]),
  ('Schrägbankdrücken', array['Incline Bench Press']::text[]),
  ('Kurzhantel-Bankdrücken', array['Dumbbell Bench Press']::text[]),
  ('Kurzhantel-Schrägbankdrücken', array['Incline Dumbbell Press']::text[]),
  ('Dips', array['Barren-Dips']::text[]),
  ('Fliegende', array['Dumbbell Fly', 'Butterfly']::text[]),
  ('Kabelzug Fliegende', array['Cable Fly', 'Cable Crossover']::text[]),
  ('Liegestütze', array['Push-ups']::text[]),
  ('Schulterdrücken', array['Overhead Press', 'Military Press']::text[]),
  ('Kurzhantel-Schulterdrücken', array['Dumbbell Shoulder Press']::text[]),
  ('Arnold Press', array[]::text[]),
  ('Seitheben', array['Lateral Raise']::text[]),
  ('Frontheben', array['Front Raise']::text[]),
  ('Reverse Fly', array['Hinteres Schulterheben']::text[]),
  ('Face Pulls', array['Face Pull']::text[]),
  ('Aufrechtes Rudern', array['Upright Row']::text[]),
  ('Klimmzüge', array['Pull-ups', 'Pull-Ups']::text[]),
  ('Chin-ups', array['Klimmzüge im Untergriff']::text[]),
  ('Latziehen', array['Lat Pulldown']::text[]),
  ('Langhantelrudern', array['Barbell Row', 'Vorgebeugtes Rudern']::text[]),
  ('Kurzhantelrudern', array['Dumbbell Row', 'Einarmiges Rudern']::text[]),
  ('Rudern am Kabelzug', array['Seated Cable Row']::text[]),
  ('T-Bar-Rudern', array['T-Bar Row']::text[]),
  ('Brustgestütztes Rudern', array['Chest-Supported Row']::text[]),
  ('Kabel-Pullover', array['Straight-Arm Pulldown']::text[]),
  ('Schulterzucken', array['Shrugs']::text[]),
  ('Bizeps-Curls', array['Biceps Curl', 'Langhantel-Curls']::text[]),
  ('Kurzhantel-Curls', array['Dumbbell Curl']::text[]),
  ('Hammer-Curls', array['Hammer Curl']::text[]),
  ('Preacher Curls', array['Scott-Curls']::text[]),
  ('Trizepsdrücken am Kabel', array['Triceps Pushdown']::text[]),
  ('Skull Crushers', array['Stirndrücken']::text[]),
  ('Französisches Drücken', array['Overhead Triceps Extension']::text[]),
  ('Enges Bankdrücken', array['Close-Grip Bench Press']::text[]),
  ('Plank', array['Unterarmstütz']::text[]),
  ('Hängendes Beinheben', array['Hanging Leg Raise']::text[]),
  ('Cable Crunch', array['Kabel-Crunches']::text[]),
  ('Ab Wheel', array['Bauchroller']::text[]),
  ('Farmer''s Walk', array['Farmers Walk']::text[])
) as v(name, aliases)
where not exists (
  select 1 from public.exercises e where e.user_id is null and lower(e.name) = lower(v.name)
);
